@startuml sequence_add_review_diagram

!theme plain
hide footbox

title Add Review Diagram

' definitions

actor User
participant "Web browser" as Browser
participant Application as App
database PostgreSQL as DB

activate App
activate DB
activate Browser

' diagram

' start interaction
User -> Browser: Input data and\nclick button
Browser -> Browser: Validate data

alt Invalid data
    User <-- Browser: Show error
end

' add to Cart
Browser -> Browser: Check token\nexp. time

alt Token expired
    Browser ->> App ++: POST /user/refresh
    App -> App: Validate token
    alt Token invalid
        Browser <<-- App: Error
        User <-- Browser: Show error
        Browser -> Browser: Redirect to Login
    end
    return JWT tokens
end

Browser ->> App ++: POST /review

App -> App: Validate token\nand data

alt Invalid token or data
    Browser <<-- App: Error
    User <-- Browser: Show error
end

App -> DB: Save review record
App <-- DB

alt Database error
    App -> App: Log error
    Browser <<-- App: Error
    User <-- Browser: Show error
end

Browser <<-- App
Browser -> Browser: Render reviews
User <-- Browser

@enduml